name: Remote Private Repo
on:
  push:
    branches: [main]
jobs:
  build:
    name: Private Repo 
    runs-on: Ubuntu-18.04
    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
         repository: ICT-CET-Activities/hiddenRepo
         path: remoteprivaterepo
         token: ${{ secrets.TOPSECRETTOKEN }}
      - name: Show hidden files
        run: |
         cd remoteprivaterepo   
         ls



